; Auto-generated. Do not edit!


(cl:in-package lebai_msgs-msg)


;//! \htmlinclude IOStatus.msg.html

(cl:defclass <IOStatus> (roslisp-msg-protocol:ros-message)
  ((robot_din
    :reader robot_din
    :initarg :robot_din
    :type (cl:vector cl:boolean)
   :initform (cl:make-array 0 :element-type 'cl:boolean :initial-element cl:nil))
   (robot_dout
    :reader robot_dout
    :initarg :robot_dout
    :type (cl:vector cl:boolean)
   :initform (cl:make-array 0 :element-type 'cl:boolean :initial-element cl:nil))
   (robot_ain
    :reader robot_ain
    :initarg :robot_ain
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (robot_aout
    :reader robot_aout
    :initarg :robot_aout
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (robot_ain_type
    :reader robot_ain_type
    :initarg :robot_ain_type
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (robot_aout_type
    :reader robot_aout_type
    :initarg :robot_aout_type
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (flange_din
    :reader flange_din
    :initarg :flange_din
    :type (cl:vector cl:boolean)
   :initform (cl:make-array 0 :element-type 'cl:boolean :initial-element cl:nil))
   (flange_dout
    :reader flange_dout
    :initarg :flange_dout
    :type (cl:vector cl:boolean)
   :initform (cl:make-array 0 :element-type 'cl:boolean :initial-element cl:nil)))
)

(cl:defclass IOStatus (<IOStatus>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IOStatus>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IOStatus)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lebai_msgs-msg:<IOStatus> is deprecated: use lebai_msgs-msg:IOStatus instead.")))

(cl:ensure-generic-function 'robot_din-val :lambda-list '(m))
(cl:defmethod robot_din-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:robot_din-val is deprecated.  Use lebai_msgs-msg:robot_din instead.")
  (robot_din m))

(cl:ensure-generic-function 'robot_dout-val :lambda-list '(m))
(cl:defmethod robot_dout-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:robot_dout-val is deprecated.  Use lebai_msgs-msg:robot_dout instead.")
  (robot_dout m))

(cl:ensure-generic-function 'robot_ain-val :lambda-list '(m))
(cl:defmethod robot_ain-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:robot_ain-val is deprecated.  Use lebai_msgs-msg:robot_ain instead.")
  (robot_ain m))

(cl:ensure-generic-function 'robot_aout-val :lambda-list '(m))
(cl:defmethod robot_aout-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:robot_aout-val is deprecated.  Use lebai_msgs-msg:robot_aout instead.")
  (robot_aout m))

(cl:ensure-generic-function 'robot_ain_type-val :lambda-list '(m))
(cl:defmethod robot_ain_type-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:robot_ain_type-val is deprecated.  Use lebai_msgs-msg:robot_ain_type instead.")
  (robot_ain_type m))

(cl:ensure-generic-function 'robot_aout_type-val :lambda-list '(m))
(cl:defmethod robot_aout_type-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:robot_aout_type-val is deprecated.  Use lebai_msgs-msg:robot_aout_type instead.")
  (robot_aout_type m))

(cl:ensure-generic-function 'flange_din-val :lambda-list '(m))
(cl:defmethod flange_din-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:flange_din-val is deprecated.  Use lebai_msgs-msg:flange_din instead.")
  (flange_din m))

(cl:ensure-generic-function 'flange_dout-val :lambda-list '(m))
(cl:defmethod flange_dout-val ((m <IOStatus>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lebai_msgs-msg:flange_dout-val is deprecated.  Use lebai_msgs-msg:flange_dout instead.")
  (flange_dout m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<IOStatus>)))
    "Constants for message type '<IOStatus>"
  '((:VOLTAGETYPE . 0)
    (:CURRENTTYPE . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'IOStatus)))
    "Constants for message type 'IOStatus"
  '((:VOLTAGETYPE . 0)
    (:CURRENTTYPE . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IOStatus>) ostream)
  "Serializes a message object of type '<IOStatus>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_din))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if ele 1 0)) ostream))
   (cl:slot-value msg 'robot_din))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_dout))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if ele 1 0)) ostream))
   (cl:slot-value msg 'robot_dout))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_ain))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'robot_ain))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_aout))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'robot_aout))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_ain_type))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'robot_ain_type))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_aout_type))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'robot_aout_type))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'flange_din))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if ele 1 0)) ostream))
   (cl:slot-value msg 'flange_din))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'flange_dout))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if ele 1 0)) ostream))
   (cl:slot-value msg 'flange_dout))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IOStatus>) istream)
  "Deserializes a message object of type '<IOStatus>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_din) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_din)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:not (cl:zerop (cl:read-byte istream)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_dout) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_dout)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:not (cl:zerop (cl:read-byte istream)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_ain) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_ain)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_aout) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_aout)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_ain_type) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_ain_type)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_aout_type) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_aout_type)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'flange_din) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'flange_din)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:not (cl:zerop (cl:read-byte istream)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'flange_dout) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'flange_dout)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:not (cl:zerop (cl:read-byte istream)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IOStatus>)))
  "Returns string type for a message object of type '<IOStatus>"
  "lebai_msgs/IOStatus")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IOStatus)))
  "Returns string type for a message object of type 'IOStatus"
  "lebai_msgs/IOStatus")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IOStatus>)))
  "Returns md5sum for a message object of type '<IOStatus>"
  "50c134754be339b506d0926e86b51aa1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IOStatus)))
  "Returns md5sum for a message object of type 'IOStatus"
  "50c134754be339b506d0926e86b51aa1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IOStatus>)))
  "Returns full string definition for message of type '<IOStatus>"
  (cl:format cl:nil "bool[] robot_din~%bool[] robot_dout~%float32[] robot_ain~%float32[] robot_aout~%uint8[] robot_ain_type~%uint8[] robot_aout_type~%bool[] flange_din~%bool[] flange_dout~%~%uint8 VOLTAGETYPE=0~%uint8 CURRENTTYPE=1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IOStatus)))
  "Returns full string definition for message of type 'IOStatus"
  (cl:format cl:nil "bool[] robot_din~%bool[] robot_dout~%float32[] robot_ain~%float32[] robot_aout~%uint8[] robot_ain_type~%uint8[] robot_aout_type~%bool[] flange_din~%bool[] flange_dout~%~%uint8 VOLTAGETYPE=0~%uint8 CURRENTTYPE=1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IOStatus>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_din) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_dout) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_ain) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_aout) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_ain_type) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_aout_type) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'flange_din) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'flange_dout) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IOStatus>))
  "Converts a ROS message object to a list"
  (cl:list 'IOStatus
    (cl:cons ':robot_din (robot_din msg))
    (cl:cons ':robot_dout (robot_dout msg))
    (cl:cons ':robot_ain (robot_ain msg))
    (cl:cons ':robot_aout (robot_aout msg))
    (cl:cons ':robot_ain_type (robot_ain_type msg))
    (cl:cons ':robot_aout_type (robot_aout_type msg))
    (cl:cons ':flange_din (flange_din msg))
    (cl:cons ':flange_dout (flange_dout msg))
))
