bool way_point_is_joint_pose
float64[] way_point_joint_pose
geometry_msgs/Pose way_point_cartesian_pose
bool end_point_is_joint_pose
float64[] end_point_joint_pose
geometry_msgs/Pose end_point_cartesian_pose
float64 circle_angle
lebai_interfaces/MoveCommon common
---
bool ret