uint32 MODE_UNCHANGED=0
uint32 MODE_OFF=1
uint32 MODE_STEADY=2
uint32 MODE_BREATH=3
uint32 MODE_ROTATE_SEGMENTED=4
uint32 MODE_ROTATE_SOLID=5
uint32 MODE_FLASH=6

uint32 SPEED_UNSPECIFIED=0
uint32 SPEED_FAST=1
uint32 SPEED_NORMAL=2
uint32 SPEED_SLOW=3

uint32 mode
uint32 speed
uint8[] color
---
lebai_interfaces/Result result
