(cl:in-package lebai_msgs-srv)
(cl:export '(WAY_POINT_IS_JOINT_POSE-VAL
          WAY_POINT_IS_JOINT_POSE
          WAY_POINT_JOINT_POSE-VAL
          WAY_POINT_JOINT_POSE
          WAY_POINT_CARTESIAN_POSE-VAL
          WAY_POINT_CARTESIAN_POSE
          END_POINT_IS_JOINT_POSE-VAL
          END_POINT_IS_JOINT_POSE
          END_POINT_JOINT_POSE-VAL
          END_POINT_JOINT_POSE
          END_POINT_CARTESIAN_POSE-VAL
          END_POINT_CARTESIAN_POSE
          CIRCLE_ANGLE-VAL
          CIRCLE_ANGLE
          COMMON-VAL
          COMMON
          EXECUTE_MODE-VAL
          EXECUTE_MODE
          RET-VAL
          RET
))