moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - lebai_trajectory_controller

lebai_trajectory_controller:
  action_ns: ""
  type: FollowJointTrajectory
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
