// Generated by gencpp from file lebai_msgs/ExecuteMode.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_EXECUTEMODE_H
#define LEBAI_MSGS_MESSAGE_EXECUTEMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lebai_msgs
{
template <class ContainerAllocator>
struct ExecuteMode_
{
  typedef ExecuteMode_<ContainerAllocator> Type;

  ExecuteMode_()
    : data(0)  {
    }
  ExecuteMode_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(EXECUTE_MODE_BUFFER)
  #undef EXECUTE_MODE_BUFFER
#endif
#if defined(_WIN32) && defined(EXECUTE_MODE_IMMED)
  #undef EXECUTE_MODE_IMMED
#endif

  enum {
    EXECUTE_MODE_BUFFER = 0u,
    EXECUTE_MODE_IMMED = 1u,
  };


  typedef boost::shared_ptr< ::lebai_msgs::ExecuteMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lebai_msgs::ExecuteMode_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteMode_

typedef ::lebai_msgs::ExecuteMode_<std::allocator<void> > ExecuteMode;

typedef boost::shared_ptr< ::lebai_msgs::ExecuteMode > ExecuteModePtr;
typedef boost::shared_ptr< ::lebai_msgs::ExecuteMode const> ExecuteModeConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lebai_msgs::ExecuteMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lebai_msgs::ExecuteMode_<ContainerAllocator1> & lhs, const ::lebai_msgs::ExecuteMode_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lebai_msgs::ExecuteMode_<ContainerAllocator1> & lhs, const ::lebai_msgs::ExecuteMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lebai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::ExecuteMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::ExecuteMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::ExecuteMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce2e0fd38d2abc7741472f6d6de5645a";
  }

  static const char* value(const ::lebai_msgs::ExecuteMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce2e0fd38d2abc77ULL;
  static const uint64_t static_value2 = 0x41472f6d6de5645aULL;
};

template<class ContainerAllocator>
struct DataType< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lebai_msgs/ExecuteMode";
  }

  static const char* value(const ::lebai_msgs::ExecuteMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 data\n"
"uint8 EXECUTE_MODE_BUFFER=0\n"
"uint8 EXECUTE_MODE_IMMED=1\n"
;
  }

  static const char* value(const ::lebai_msgs::ExecuteMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lebai_msgs::ExecuteMode_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_EXECUTEMODE_H
