// Generated by gencpp from file lebai_msgs/MoveJointRequest.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_MOVEJOINTREQUEST_H
#define LEBAI_MSGS_MESSAGE_MOVEJOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <lebai_msgs/MoveCommon.h>
#include <lebai_msgs/ExecuteMode.h>

namespace lebai_msgs
{
template <class ContainerAllocator>
struct MoveJointRequest_
{
  typedef MoveJointRequest_<ContainerAllocator> Type;

  MoveJointRequest_()
    : is_joint_pose(false)
    , joint_pose()
    , cartesian_pose()
    , common()
    , execute_mode()  {
    }
  MoveJointRequest_(const ContainerAllocator& _alloc)
    : is_joint_pose(false)
    , joint_pose(_alloc)
    , cartesian_pose(_alloc)
    , common(_alloc)
    , execute_mode(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_joint_pose_type;
  _is_joint_pose_type is_joint_pose;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_pose_type;
  _joint_pose_type joint_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _cartesian_pose_type;
  _cartesian_pose_type cartesian_pose;

   typedef  ::lebai_msgs::MoveCommon_<ContainerAllocator>  _common_type;
  _common_type common;

   typedef  ::lebai_msgs::ExecuteMode_<ContainerAllocator>  _execute_mode_type;
  _execute_mode_type execute_mode;





  typedef boost::shared_ptr< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveJointRequest_

typedef ::lebai_msgs::MoveJointRequest_<std::allocator<void> > MoveJointRequest;

typedef boost::shared_ptr< ::lebai_msgs::MoveJointRequest > MoveJointRequestPtr;
typedef boost::shared_ptr< ::lebai_msgs::MoveJointRequest const> MoveJointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lebai_msgs::MoveJointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lebai_msgs::MoveJointRequest_<ContainerAllocator1> & lhs, const ::lebai_msgs::MoveJointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.is_joint_pose == rhs.is_joint_pose &&
    lhs.joint_pose == rhs.joint_pose &&
    lhs.cartesian_pose == rhs.cartesian_pose &&
    lhs.common == rhs.common &&
    lhs.execute_mode == rhs.execute_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lebai_msgs::MoveJointRequest_<ContainerAllocator1> & lhs, const ::lebai_msgs::MoveJointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lebai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "599b6e59dffcb2d7897c91370cc382fd";
  }

  static const char* value(const ::lebai_msgs::MoveJointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x599b6e59dffcb2d7ULL;
  static const uint64_t static_value2 = 0x897c91370cc382fdULL;
};

template<class ContainerAllocator>
struct DataType< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lebai_msgs/MoveJointRequest";
  }

  static const char* value(const ::lebai_msgs::MoveJointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_joint_pose\n"
"float64[] joint_pose\n"
"geometry_msgs/Pose cartesian_pose\n"
"lebai_msgs/MoveCommon common\n"
"lebai_msgs/ExecuteMode execute_mode\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: lebai_msgs/MoveCommon\n"
"float64 vel\n"
"float64 acc\n"
"float64 time\n"
"bool is_continous_mode\n"
"# 0: normal move, 1: smooth move\n"
"uint8 continuation_type\n"
"# until data\n"
"bool until\n"
"lebai_msgs/UntilInfo until_info\n"
"================================================================================\n"
"MSG: lebai_msgs/UntilInfo\n"
"uint8 io_express_logic\n"
"lebai_msgs/IOConditionalExpress[] io_express\n"
"\n"
"uint8 LOGIC_AND=0\n"
"uint8 LOGIC_OR=1\n"
"\n"
"\n"
"================================================================================\n"
"MSG: lebai_msgs/IOConditionalExpress\n"
"uint32 group\n"
"uint32 pin\n"
"uint32 type\n"
"float64 float_value\n"
"uint8 uint_value\n"
"uint8 logic_operation\n"
"\n"
"uint8 GROUP_ROBOT=0\n"
"uint8 GROUP_FLANGE=1\n"
"\n"
"uint8 TYPE_ANALOG=0\n"
"uint8 TYPE_DIGITAL=1\n"
"\n"
"# great >\n"
"uint8 LOGIC_OP_GT=0\n"
"# great and equal >=\n"
"uint8 LOGIC_OP_GE=1\n"
"# equal\n"
"uint8 LOGIC_OP_EQ=2\n"
"# not equal\n"
"uint8 LOGIC_OP_NE=3\n"
"# less than\n"
"uint8 LOGIC_OP_LT=4\n"
"# less than and equal\n"
"uint8 LOGIC_OP_LE=5\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: lebai_msgs/ExecuteMode\n"
"uint8 data\n"
"uint8 EXECUTE_MODE_BUFFER=0\n"
"uint8 EXECUTE_MODE_IMMED=1\n"
;
  }

  static const char* value(const ::lebai_msgs::MoveJointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_joint_pose);
      stream.next(m.joint_pose);
      stream.next(m.cartesian_pose);
      stream.next(m.common);
      stream.next(m.execute_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveJointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lebai_msgs::MoveJointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lebai_msgs::MoveJointRequest_<ContainerAllocator>& v)
  {
    s << indent << "is_joint_pose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_joint_pose);
    s << indent << "joint_pose[]" << std::endl;
    for (size_t i = 0; i < v.joint_pose.size(); ++i)
    {
      s << indent << "  joint_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_pose[i]);
    }
    s << indent << "cartesian_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.cartesian_pose);
    s << indent << "common: ";
    s << std::endl;
    Printer< ::lebai_msgs::MoveCommon_<ContainerAllocator> >::stream(s, indent + "  ", v.common);
    s << indent << "execute_mode: ";
    s << std::endl;
    Printer< ::lebai_msgs::ExecuteMode_<ContainerAllocator> >::stream(s, indent + "  ", v.execute_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_MOVEJOINTREQUEST_H
