// Generated by gencpp from file lebai_msgs/MoveLine.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_MOVELINE_H
#define LEBAI_MSGS_MESSAGE_MOVELINE_H

#include <ros/service_traits.h>


#include <lebai_msgs/MoveLineRequest.h>
#include <lebai_msgs/MoveLineResponse.h>


namespace lebai_msgs
{

struct MoveLine
{

typedef MoveLineRequest Request;
typedef MoveLineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLine
} // namespace lebai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lebai_msgs::MoveLine > {
  static const char* value()
  {
    return "d7ba5f85f827d398c331d4fd7812bf30";
  }

  static const char* value(const ::lebai_msgs::MoveLine&) { return value(); }
};

template<>
struct DataType< ::lebai_msgs::MoveLine > {
  static const char* value()
  {
    return "lebai_msgs/MoveLine";
  }

  static const char* value(const ::lebai_msgs::MoveLine&) { return value(); }
};


// service_traits::MD5Sum< ::lebai_msgs::MoveLineRequest> should match
// service_traits::MD5Sum< ::lebai_msgs::MoveLine >
template<>
struct MD5Sum< ::lebai_msgs::MoveLineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::MoveLine >::value();
  }
  static const char* value(const ::lebai_msgs::MoveLineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::MoveLineRequest> should match
// service_traits::DataType< ::lebai_msgs::MoveLine >
template<>
struct DataType< ::lebai_msgs::MoveLineRequest>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::MoveLine >::value();
  }
  static const char* value(const ::lebai_msgs::MoveLineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lebai_msgs::MoveLineResponse> should match
// service_traits::MD5Sum< ::lebai_msgs::MoveLine >
template<>
struct MD5Sum< ::lebai_msgs::MoveLineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::MoveLine >::value();
  }
  static const char* value(const ::lebai_msgs::MoveLineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::MoveLineResponse> should match
// service_traits::DataType< ::lebai_msgs::MoveLine >
template<>
struct DataType< ::lebai_msgs::MoveLineResponse>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::MoveLine >::value();
  }
  static const char* value(const ::lebai_msgs::MoveLineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_MOVELINE_H
