// Generated by gencpp from file lebai_msgs/MoveJoint.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_MOVEJOINT_H
#define LEBAI_MSGS_MESSAGE_MOVEJOINT_H

#include <ros/service_traits.h>


#include <lebai_msgs/MoveJointRequest.h>
#include <lebai_msgs/MoveJointResponse.h>


namespace lebai_msgs
{

struct MoveJoint
{

typedef MoveJointRequest Request;
typedef MoveJointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJoint
} // namespace lebai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lebai_msgs::MoveJoint > {
  static const char* value()
  {
    return "d7ba5f85f827d398c331d4fd7812bf30";
  }

  static const char* value(const ::lebai_msgs::MoveJoint&) { return value(); }
};

template<>
struct DataType< ::lebai_msgs::MoveJoint > {
  static const char* value()
  {
    return "lebai_msgs/MoveJoint";
  }

  static const char* value(const ::lebai_msgs::MoveJoint&) { return value(); }
};


// service_traits::MD5Sum< ::lebai_msgs::MoveJointRequest> should match
// service_traits::MD5Sum< ::lebai_msgs::MoveJoint >
template<>
struct MD5Sum< ::lebai_msgs::MoveJointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::MoveJoint >::value();
  }
  static const char* value(const ::lebai_msgs::MoveJointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::MoveJointRequest> should match
// service_traits::DataType< ::lebai_msgs::MoveJoint >
template<>
struct DataType< ::lebai_msgs::MoveJointRequest>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::MoveJoint >::value();
  }
  static const char* value(const ::lebai_msgs::MoveJointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lebai_msgs::MoveJointResponse> should match
// service_traits::MD5Sum< ::lebai_msgs::MoveJoint >
template<>
struct MD5Sum< ::lebai_msgs::MoveJointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::MoveJoint >::value();
  }
  static const char* value(const ::lebai_msgs::MoveJointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::MoveJointResponse> should match
// service_traits::DataType< ::lebai_msgs::MoveJoint >
template<>
struct DataType< ::lebai_msgs::MoveJointResponse>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::MoveJoint >::value();
  }
  static const char* value(const ::lebai_msgs::MoveJointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_MOVEJOINT_H
