// Generated by gencpp from file lebai_msgs/MoveCircleResponse.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_MOVECIRCLERESPONSE_H
#define LEBAI_MSGS_MESSAGE_MOVECIRCLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lebai_msgs
{
template <class ContainerAllocator>
struct MoveCircleResponse_
{
  typedef MoveCircleResponse_<ContainerAllocator> Type;

  MoveCircleResponse_()
    : ret(false)  {
    }
  MoveCircleResponse_(const ContainerAllocator& _alloc)
    : ret(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveCircleResponse_

typedef ::lebai_msgs::MoveCircleResponse_<std::allocator<void> > MoveCircleResponse;

typedef boost::shared_ptr< ::lebai_msgs::MoveCircleResponse > MoveCircleResponsePtr;
typedef boost::shared_ptr< ::lebai_msgs::MoveCircleResponse const> MoveCircleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator1> & lhs, const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator1> & lhs, const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lebai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2cc9e9d8c464550ULL;
  static const uint64_t static_value2 = 0x830df49c160979adULL;
};

template<class ContainerAllocator>
struct DataType< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lebai_msgs/MoveCircleResponse";
  }

  static const char* value(const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ret\n"
;
  }

  static const char* value(const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveCircleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lebai_msgs::MoveCircleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lebai_msgs::MoveCircleResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_MOVECIRCLERESPONSE_H
