// Generated by gencpp from file lebai_msgs/SetAMode.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_SETAMODE_H
#define LEBAI_MSGS_MESSAGE_SETAMODE_H

#include <ros/service_traits.h>


#include <lebai_msgs/SetAModeRequest.h>
#include <lebai_msgs/SetAModeResponse.h>


namespace lebai_msgs
{

struct SetAMode
{

typedef SetAModeRequest Request;
typedef SetAModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAMode
} // namespace lebai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lebai_msgs::SetAMode > {
  static const char* value()
  {
    return "db41913f133aefb2bfdc45acc60725b5";
  }

  static const char* value(const ::lebai_msgs::SetAMode&) { return value(); }
};

template<>
struct DataType< ::lebai_msgs::SetAMode > {
  static const char* value()
  {
    return "lebai_msgs/SetAMode";
  }

  static const char* value(const ::lebai_msgs::SetAMode&) { return value(); }
};


// service_traits::MD5Sum< ::lebai_msgs::SetAModeRequest> should match
// service_traits::MD5Sum< ::lebai_msgs::SetAMode >
template<>
struct MD5Sum< ::lebai_msgs::SetAModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetAMode >::value();
  }
  static const char* value(const ::lebai_msgs::SetAModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetAModeRequest> should match
// service_traits::DataType< ::lebai_msgs::SetAMode >
template<>
struct DataType< ::lebai_msgs::SetAModeRequest>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetAMode >::value();
  }
  static const char* value(const ::lebai_msgs::SetAModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lebai_msgs::SetAModeResponse> should match
// service_traits::MD5Sum< ::lebai_msgs::SetAMode >
template<>
struct MD5Sum< ::lebai_msgs::SetAModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetAMode >::value();
  }
  static const char* value(const ::lebai_msgs::SetAModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetAModeResponse> should match
// service_traits::DataType< ::lebai_msgs::SetAMode >
template<>
struct DataType< ::lebai_msgs::SetAModeResponse>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetAMode >::value();
  }
  static const char* value(const ::lebai_msgs::SetAModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_SETAMODE_H
