// Generated by gencpp from file lebai_msgs/SetAOutRequest.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_SETAOUTREQUEST_H
#define LEBAI_MSGS_MESSAGE_SETAOUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lebai_msgs
{
template <class ContainerAllocator>
struct SetAOutRequest_
{
  typedef SetAOutRequest_<ContainerAllocator> Type;

  SetAOutRequest_()
    : group(0)
    , index(0)
    , value(0.0)  {
    }
  SetAOutRequest_(const ContainerAllocator& _alloc)
    : group(0)
    , index(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _group_type;
  _group_type group;

   typedef uint16_t _index_type;
  _index_type index;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetAOutRequest_

typedef ::lebai_msgs::SetAOutRequest_<std::allocator<void> > SetAOutRequest;

typedef boost::shared_ptr< ::lebai_msgs::SetAOutRequest > SetAOutRequestPtr;
typedef boost::shared_ptr< ::lebai_msgs::SetAOutRequest const> SetAOutRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lebai_msgs::SetAOutRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lebai_msgs::SetAOutRequest_<ContainerAllocator1> & lhs, const ::lebai_msgs::SetAOutRequest_<ContainerAllocator2> & rhs)
{
  return lhs.group == rhs.group &&
    lhs.index == rhs.index &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lebai_msgs::SetAOutRequest_<ContainerAllocator1> & lhs, const ::lebai_msgs::SetAOutRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lebai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea7eca226d31910fccddba8c483e4857";
  }

  static const char* value(const ::lebai_msgs::SetAOutRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea7eca226d31910fULL;
  static const uint64_t static_value2 = 0xccddba8c483e4857ULL;
};

template<class ContainerAllocator>
struct DataType< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lebai_msgs/SetAOutRequest";
  }

  static const char* value(const ::lebai_msgs::SetAOutRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 group\n"
"uint16 index\n"
"float64 value\n"
;
  }

  static const char* value(const ::lebai_msgs::SetAOutRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group);
      stream.next(m.index);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAOutRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lebai_msgs::SetAOutRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lebai_msgs::SetAOutRequest_<ContainerAllocator>& v)
  {
    s << indent << "group: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.group);
    s << indent << "index: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.index);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_SETAOUTREQUEST_H
