// Generated by gencpp from file lebai_msgs/SetAOut.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_SETAOUT_H
#define LEBAI_MSGS_MESSAGE_SETAOUT_H

#include <ros/service_traits.h>


#include <lebai_msgs/SetAOutRequest.h>
#include <lebai_msgs/SetAOutResponse.h>


namespace lebai_msgs
{

struct SetAOut
{

typedef SetAOutRequest Request;
typedef SetAOutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAOut
} // namespace lebai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lebai_msgs::SetAOut > {
  static const char* value()
  {
    return "51928732046ffb5b5606f765ba7fcd8b";
  }

  static const char* value(const ::lebai_msgs::SetAOut&) { return value(); }
};

template<>
struct DataType< ::lebai_msgs::SetAOut > {
  static const char* value()
  {
    return "lebai_msgs/SetAOut";
  }

  static const char* value(const ::lebai_msgs::SetAOut&) { return value(); }
};


// service_traits::MD5Sum< ::lebai_msgs::SetAOutRequest> should match
// service_traits::MD5Sum< ::lebai_msgs::SetAOut >
template<>
struct MD5Sum< ::lebai_msgs::SetAOutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetAOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetAOutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetAOutRequest> should match
// service_traits::DataType< ::lebai_msgs::SetAOut >
template<>
struct DataType< ::lebai_msgs::SetAOutRequest>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetAOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetAOutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lebai_msgs::SetAOutResponse> should match
// service_traits::MD5Sum< ::lebai_msgs::SetAOut >
template<>
struct MD5Sum< ::lebai_msgs::SetAOutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetAOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetAOutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetAOutResponse> should match
// service_traits::DataType< ::lebai_msgs::SetAOut >
template<>
struct DataType< ::lebai_msgs::SetAOutResponse>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetAOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetAOutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_SETAOUT_H
