// Generated by gencpp from file lebai_msgs/SetAOutModeRequest.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_SETAOUTMODEREQUEST_H
#define LEBAI_MSGS_MESSAGE_SETAOUTMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lebai_msgs
{
template <class ContainerAllocator>
struct SetAOutModeRequest_
{
  typedef SetAOutModeRequest_<ContainerAllocator> Type;

  SetAOutModeRequest_()
    : group(0)
    , index(0)
    , mode(0)  {
    }
  SetAOutModeRequest_(const ContainerAllocator& _alloc)
    : group(0)
    , index(0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _group_type;
  _group_type group;

   typedef uint16_t _index_type;
  _index_type index;

   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetAOutModeRequest_

typedef ::lebai_msgs::SetAOutModeRequest_<std::allocator<void> > SetAOutModeRequest;

typedef boost::shared_ptr< ::lebai_msgs::SetAOutModeRequest > SetAOutModeRequestPtr;
typedef boost::shared_ptr< ::lebai_msgs::SetAOutModeRequest const> SetAOutModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator1> & lhs, const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.group == rhs.group &&
    lhs.index == rhs.index &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator1> & lhs, const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lebai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4af607cdbbd245f2058b461b68608500";
  }

  static const char* value(const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4af607cdbbd245f2ULL;
  static const uint64_t static_value2 = 0x058b461b68608500ULL;
};

template<class ContainerAllocator>
struct DataType< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lebai_msgs/SetAOutModeRequest";
  }

  static const char* value(const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 group\n"
"uint16 index\n"
"uint8 mode\n"
;
  }

  static const char* value(const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.group);
      stream.next(m.index);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetAOutModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lebai_msgs::SetAOutModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "group: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.group);
    s << indent << "index: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.index);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_SETAOUTMODEREQUEST_H
