// Generated by gencpp from file lebai_msgs/SetDOut.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_SETDOUT_H
#define LEBAI_MSGS_MESSAGE_SETDOUT_H

#include <ros/service_traits.h>


#include <lebai_msgs/SetDOutRequest.h>
#include <lebai_msgs/SetDOutResponse.h>


namespace lebai_msgs
{

struct SetDOut
{

typedef SetDOutRequest Request;
typedef SetDOutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDOut
} // namespace lebai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lebai_msgs::SetDOut > {
  static const char* value()
  {
    return "e6191b92a4b149f13f17282b8739af44";
  }

  static const char* value(const ::lebai_msgs::SetDOut&) { return value(); }
};

template<>
struct DataType< ::lebai_msgs::SetDOut > {
  static const char* value()
  {
    return "lebai_msgs/SetDOut";
  }

  static const char* value(const ::lebai_msgs::SetDOut&) { return value(); }
};


// service_traits::MD5Sum< ::lebai_msgs::SetDOutRequest> should match
// service_traits::MD5Sum< ::lebai_msgs::SetDOut >
template<>
struct MD5Sum< ::lebai_msgs::SetDOutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetDOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetDOutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetDOutRequest> should match
// service_traits::DataType< ::lebai_msgs::SetDOut >
template<>
struct DataType< ::lebai_msgs::SetDOutRequest>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetDOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetDOutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lebai_msgs::SetDOutResponse> should match
// service_traits::MD5Sum< ::lebai_msgs::SetDOut >
template<>
struct MD5Sum< ::lebai_msgs::SetDOutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetDOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetDOutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetDOutResponse> should match
// service_traits::DataType< ::lebai_msgs::SetDOut >
template<>
struct DataType< ::lebai_msgs::SetDOutResponse>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetDOut >::value();
  }
  static const char* value(const ::lebai_msgs::SetDOutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_SETDOUT_H
