// Generated by gencpp from file lebai_msgs/SetDO.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_SETDO_H
#define LEBAI_MSGS_MESSAGE_SETDO_H

#include <ros/service_traits.h>


#include <lebai_msgs/SetDORequest.h>
#include <lebai_msgs/SetDOResponse.h>


namespace lebai_msgs
{

struct SetDO
{

typedef SetDORequest Request;
typedef SetDOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDO
} // namespace lebai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lebai_msgs::SetDO > {
  static const char* value()
  {
    return "5a536dfb6aaff1ccac47c5a754efe2e6";
  }

  static const char* value(const ::lebai_msgs::SetDO&) { return value(); }
};

template<>
struct DataType< ::lebai_msgs::SetDO > {
  static const char* value()
  {
    return "lebai_msgs/SetDO";
  }

  static const char* value(const ::lebai_msgs::SetDO&) { return value(); }
};


// service_traits::MD5Sum< ::lebai_msgs::SetDORequest> should match
// service_traits::MD5Sum< ::lebai_msgs::SetDO >
template<>
struct MD5Sum< ::lebai_msgs::SetDORequest>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetDO >::value();
  }
  static const char* value(const ::lebai_msgs::SetDORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetDORequest> should match
// service_traits::DataType< ::lebai_msgs::SetDO >
template<>
struct DataType< ::lebai_msgs::SetDORequest>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetDO >::value();
  }
  static const char* value(const ::lebai_msgs::SetDORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lebai_msgs::SetDOResponse> should match
// service_traits::MD5Sum< ::lebai_msgs::SetDO >
template<>
struct MD5Sum< ::lebai_msgs::SetDOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetDO >::value();
  }
  static const char* value(const ::lebai_msgs::SetDOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetDOResponse> should match
// service_traits::DataType< ::lebai_msgs::SetDO >
template<>
struct DataType< ::lebai_msgs::SetDOResponse>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetDO >::value();
  }
  static const char* value(const ::lebai_msgs::SetDOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_SETDO_H
