// Generated by gencpp from file lebai_msgs/SetGripper.msg
// DO NOT EDIT!


#ifndef LEBAI_MSGS_MESSAGE_SETGRIPPER_H
#define LEBAI_MSGS_MESSAGE_SETGRIPPER_H

#include <ros/service_traits.h>


#include <lebai_msgs/SetGripperRequest.h>
#include <lebai_msgs/SetGripperResponse.h>


namespace lebai_msgs
{

struct SetGripper
{

typedef SetGripperRequest Request;
typedef SetGripperResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGripper
} // namespace lebai_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lebai_msgs::SetGripper > {
  static const char* value()
  {
    return "38cc51b5a105d56ff2e64d1889e45a66";
  }

  static const char* value(const ::lebai_msgs::SetGripper&) { return value(); }
};

template<>
struct DataType< ::lebai_msgs::SetGripper > {
  static const char* value()
  {
    return "lebai_msgs/SetGripper";
  }

  static const char* value(const ::lebai_msgs::SetGripper&) { return value(); }
};


// service_traits::MD5Sum< ::lebai_msgs::SetGripperRequest> should match
// service_traits::MD5Sum< ::lebai_msgs::SetGripper >
template<>
struct MD5Sum< ::lebai_msgs::SetGripperRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetGripper >::value();
  }
  static const char* value(const ::lebai_msgs::SetGripperRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetGripperRequest> should match
// service_traits::DataType< ::lebai_msgs::SetGripper >
template<>
struct DataType< ::lebai_msgs::SetGripperRequest>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetGripper >::value();
  }
  static const char* value(const ::lebai_msgs::SetGripperRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lebai_msgs::SetGripperResponse> should match
// service_traits::MD5Sum< ::lebai_msgs::SetGripper >
template<>
struct MD5Sum< ::lebai_msgs::SetGripperResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lebai_msgs::SetGripper >::value();
  }
  static const char* value(const ::lebai_msgs::SetGripperResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lebai_msgs::SetGripperResponse> should match
// service_traits::DataType< ::lebai_msgs::SetGripper >
template<>
struct DataType< ::lebai_msgs::SetGripperResponse>
{
  static const char* value()
  {
    return DataType< ::lebai_msgs::SetGripper >::value();
  }
  static const char* value(const ::lebai_msgs::SetGripperResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEBAI_MSGS_MESSAGE_SETGRIPPER_H
