robot1/controller_joint_names: ['robot1_joint_1', 'robot1_joint_2', 'robot1_joint_3', 'robot1_joint_4', 'robot1_joint_5', 'robot1_joint_6']
robot2/controller_joint_names: ['robot2_joint_1', 'robot2_joint_2', 'robot2_joint_3', 'robot2_joint_4', 'robot2_joint_5', 'robot2_joint_6']

